import type { PuzzlePayload } from "./types";

/**
 * SvgDiagram — a deterministic teaching diagram drawn server-side and inlined as SVG.
 *
 * Display-only: the tutor puts a labelled structure on the Learn panel (a cell, a circuit, a
 * wave, the solar system) and teaches from it. The markup is generated by
 * `svg_diagram_service` from validated params — never model-authored — so it renders instantly,
 * scales crisply, and can't mislabel the way a generated image does.
 */
export default function SvgDiagram({ payload }: { payload: PuzzlePayload }) {
  const svg = (payload.params.svg as string) || "";
  const caption = (payload.params.caption as string) || payload.prompt || "";

  return (
    <div style={{
      width: "100%", height: "100%", display: "flex", flexDirection: "column",
      alignItems: "center", justifyContent: "center", gap: 12, padding: "8px 16px",
      overflow: "auto", background: "#fff",
    }}>
      {svg ? (
        <div
          // Server-generated markup from a fixed template set (no model-authored HTML).
          dangerouslySetInnerHTML={{ __html: svg }}
          style={{ width: "100%", maxWidth: 720, maxHeight: "100%", display: "flex", justifyContent: "center" }}
        />
      ) : (
        <span style={{ color: "#94a3b8", fontSize: 14 }}>The diagram couldn't be drawn.</span>
      )}
      {caption && (
        <p style={{ margin: 0, fontSize: 14, fontWeight: 600, color: "#334155", textAlign: "center" }}>
          {caption}
        </p>
      )}
    </div>
  );
}
